name: fastapi-demo
dependencies:
  - python=3.6.12
  - pip
  - pip:
    - fastapi
    - pandas
    - pydantic
    - typing-extensions
    - graphene
    - black[d]
    - uvicorn[standard]
    - sqlalchemy
    - graphene-pydantic
    - Pydantic-SQLAlchemy
    - psycopg2
    - Faker
    - pandas
    - xgboost
    - scikit-learn
    - arrow
    - dohq-artifactory